language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.4.2
  - DJANGO=Django==1.5.0
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install --use-mirrors $DJANGO
  - pip install --use-mirrors coverage coveralls

script:
  - coverage run -a setup.py test
  - coverage report

after_success: coveralls
