# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CIMResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=8)),
                ('result_code', models.CharField(choices=[(b'I00001', b'Successful'), (b'I00003', b'The record has already been deleted.'), (b'E00001', b'An error occurred during processing. Please try again.'), (b'E00002', b'The content-type specified is not supported.'), (b'E00003', b'An error occurred while parsing the XML request.'), (b'E00004', b'The name of the requested API method is invalid.'), (b'E00005', b'The merchantAuthentication.transactionKey is invalid or not present.'), (b'E00006', b'The merchantAuthentication.name is invalid or not present.'), (b'E00007', b'User authentication failed due to invalid authentication values.'), (b'E00008', b'User authentication failed. The payment gateway account or user is inactive.'), (b'E00009', b'The payment gateway account is in Test Mode. The request cannot be processed.'), (b'E00010', b'User authentication failed. You do not have the appropriate permissions.'), (b'E00011', b'Access denied. You do not have the appropriate permissions.'), (b'E00013', b'The field is invalid.'), (b'E00014', b'A required field is not present.'), (b'E00015', b'The field length is invalid.'), (b'E00016', b'The field type is invalid.'), (b'E00019', b'The customer taxId or driversLicense information is required.'), (b'E00027', b'The transaction was unsuccessful.'), (b'E00029', b'Payment information is required.'), (b'E00039', b'A duplicate record already exists.'), (b'E00040', b'The record cannot be found.'), (b'E00041', b'One or more fields must contain a value.'), (b'E00042', b'The maximum number of payment profiles for the customer profile has been reached.'), (b'E00043', b'The maximum number of shipping addresses for the customer profile has been reached.'), (b'E00044', b'Customer Information Manager is not enabled.'), (b'E00045', b'The root node does not reference a valid XML namespace.'), (b'E00051', b'The original transaction was not issued for this payment profile.')], max_length=8)),
                ('result_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPaymentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_profile_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('fax_number', models.CharField(blank=True, max_length=25)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('zip', models.CharField(blank=True, max_length=20, verbose_name=b'ZIP')),
                ('country', models.CharField(blank=True, max_length=60)),
                ('card_number', models.CharField(blank=True, max_length=16)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(choices=[(b'1', b'Approved'), (b'2', b'Declined'), (b'3', b'Error'), (b'4', b'Held for Review')], max_length=2)),
                ('response_subcode', models.CharField(max_length=10)),
                ('response_reason_code', models.CharField(max_length=15)),
                ('response_reason_text', models.TextField()),
                ('auth_code', models.CharField(max_length=10)),
                ('avs_code', models.CharField(choices=[(b'A', b'Address (Street) matches, ZIP does not'), (b'B', b'Address information not provided for AVS check'), (b'E', b'AVS error'), (b'G', b'Non-U.S. Card Issuing Bank'), (b'N', b'No Match on Address (Street) or ZIP'), (b'P', b'AVS not applicable for this transaction'), (b'R', b'Retry - System unavailable or timed out'), (b'S', b'Service not supported by issuer'), (b'U', b'Address information is unavailable'), (b'W', b'Nine digit ZIP matches, Address (Street) does not'), (b'X', b'Address (Street) and nine digit ZIP match'), (b'Y', b'Address (Street) and five digit ZIP match'), (b'Z', b'Five digit ZIP matches, Address (Street) does not')], max_length=10)),
                ('trans_id', models.CharField(db_index=True, max_length=255)),
                ('invoice_num', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=16)),
                ('method', models.CharField(choices=[(b'CC', b'Credit Card'), (b'ECHECK', b'eCheck')], max_length=10)),
                ('type', models.CharField(choices=[(b'auth_capture', b'Authorize and Capture'), (b'auth_only', b'Authorize only'), (b'credit', b'Credit'), (b'prior_auth_capture', b'Prior capture'), (b'void', b'Void')], db_index=True, max_length=20)),
                ('cust_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('zip', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=25)),
                ('fax', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
                ('ship_to_first_name', models.CharField(blank=True, max_length=50)),
                ('ship_to_last_name', models.CharField(blank=True, max_length=50)),
                ('ship_to_company', models.CharField(blank=True, max_length=50)),
                ('ship_to_address', models.CharField(blank=True, max_length=60)),
                ('ship_to_city', models.CharField(blank=True, max_length=40)),
                ('ship_to_state', models.CharField(blank=True, max_length=40)),
                ('ship_to_zip', models.CharField(blank=True, max_length=20)),
                ('ship_to_country', models.CharField(blank=True, max_length=60)),
                ('tax', models.CharField(blank=True, max_length=16)),
                ('duty', models.CharField(blank=True, max_length=16)),
                ('freight', models.CharField(blank=True, max_length=16)),
                ('tax_exempt', models.CharField(blank=True, max_length=16)),
                ('po_num', models.CharField(blank=True, max_length=25)),
                ('MD5_Hash', models.CharField(max_length=255)),
                ('cvv2_resp_code', models.CharField(blank=True, choices=[(b'M', b'Match'), (b'N', b'No Match'), (b'P', b'Not Processed'), (b'S', b'Should have been present'), (b'U', b'Issuer unable to process request')], max_length=2)),
                ('cavv_response', models.CharField(blank=True, choices=[(b'', b'CAVV not validated'), (b'0', b'CAVV not validated because erroneous data was submitted'), (b'1', b'CAVV failed validation'), (b'2', b'CAVV passed validation'), (b'3', b'CAVV validation could not be performed; issuer attempt incomplete'), (b'4', b'CAVV validation could not be performed; issuer system error'), (b'5', b'Reserved for future use'), (b'6', b'Reserved for future use'), (b'7', b'CAVV attempt - failed validation - issuer available (U.S.-issued card/non-U.S acquirer)'), (b'8', b'CAVV attempt - passed validation - issuer available (U.S.-issued card/non-U.S. acquirer)'), (b'9', b'CAVV attempt - failed validation - issuer unavailable (U.S.-issued card/non-U.S. acquirer)'), (b'A', b'CAVV attempt - passed validation - issuer unavailable (U.S.-issued card/non-U.S. acquirer)'), (b'B', b'CAVV passed validation, information only, no liability shift')], max_length=2)),
                ('test_request', models.CharField(blank=True, default=b'FALSE', max_length=10)),
                ('card_type', models.CharField(blank=True, default=b'', max_length=10)),
                ('account_number', models.CharField(blank=True, default=b'', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customerpaymentprofile',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to='authorizenet.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='cimresponse',
            name='transaction_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorizenet.Response'),
        ),
    ]
