# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('authorizenet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ]
        ),
            
        migrations.CreateModel(
            name='CustomerPaymentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_profile_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('fax_number', models.CharField(blank=True, max_length=25)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('zip', models.CharField(blank=True, max_length=20, verbose_name=b'ZIP')),
                ('country', models.CharField(blank=True, max_length=60)),
                ('card_number', models.CharField(blank=True, max_length=16)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to=settings.AUTH_USER_MODEL)),
                ],
            ),
        migrations.AddField(
            model_name='customerpaymentprofile',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to='authorizenet.CustomerProfile'),
        )       
        
    ]
